### ISSUE TITLE
Move `evm_version` from fork config to network config

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape-foundry#89]
### Overview

It would be useful to be able to run anvil in a non-forked configuration using different evm rules, such as right now I am trying to test an EIP from Cancun while Anvil is still using Paris rules by default

### Specification

Move it to the top level config like following
```yaml
foundry:
  evm_version: str = "latest"  # default in anvil
```

### Dependencies

This will definitely conflict with how evm version works with fork networks

could be related to #88

**Comment by antazoey** [comment]
Why not have it both at top level and in the forks?

**Comment by antazoey** [comment]
OK I got the non-breaking change version in the attached PR
you can set the evm-version at foundry's config, root, not in the forks.
the forks still work, but if they are not set, it will use the global one.

I think this is better because it gives you more control if you need it, but you can also just use the root level evm-version for ease.

**Comment by fubuloubu** [comment]
Was fooling around with this today, I'm not sure if this actually works. At least, the `--hardfork prague` flag isn't showing up when I do:

```yaml
foundry:
  evm_verison: prague
```
